project:
  type: website
  output-dir: docs

website:
  title: "Landslide Susceptibility"
  navbar:
    search: true
    left:
      - The_Plan.qmd
      - text: "Landslide Initiation"
        href: Initiation.qmd
      
  sidebar:
    - title: "Landslide Initiation"
      style: "docked"
      contents:
        - text: "Introduction"
          href: Initiation.qmd
        - text: "Factor-of-Safety"
          href: FoS.qmd
        - text: "Predictors"
          href: Modeling.qmd
        - text: "Point Patterns"
          href: Spatial_Point_Processes.qmd
        - text: "Sampling"
          href: Sample.qmd
        - text: "Creating training datasets"
          href: Create_training_datasets.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
engine: knitr

editor: visual

bibliography:
  - references.bib
