project:
  type: website
  output-dir: docs

website:
  title: "Wrangell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - The_Plan.qmd
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Initiation"
        href: Initiation.qmd
      - section: "Factor-of-Safety"
        contents:
        - FoS.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

