project:
  type: website
  output-dir: docs
  
website:
  title: "Wrangell"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - The_Plan.qmd
      - text: "Landslide Initiation"
        href: Initiation.qmd
      
  sidebar:
    - title: "Landslide Initiation"
      style: "docked"
      contents:
        - text: "Introduction"
          href: Initiation.qmd
        - text: "Initiation Sites"
          href: Modeling.qmd
        - text: "Factor-of-Safety"
          href: FoS.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
bibliography: references.bib
